### ISSUE TITLE
"Coroma" library import issue

### ISSUE THREAD

**Issue by Abhayakarmach** [Abhayakarmach/CMPE188_HeartFailure#1]
Need to address this issue. Most likely we need to find an alternative for this library. 

![Capture](https://user-images.githubusercontent.com/54560353/98845163-2ab56e80-2402-11eb-981f-3b66aabf4286.PNG)

**Comment by benjamin0821** [comment]
![image](https://user-images.githubusercontent.com/54384110/98901850-5881ce00-2469-11eb-893e-c43c0610c5b6.png)

you would have to run this line of code first

**Comment by Abhayakarmach** [comment]
I didn't know we had to run the pip install line in .ipynb files. Thanks!
